# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: imranpnt
# "service" is the name of this project. This will also be added to your AWS resource names.
service: nodejs-api

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
      MONGODB_URI: 'mongodb+srv://db_username:db_password@aws-lambda.fm3hq.mongodb.net/?retryWrites=true&w=majority&appName=aws-lambda'

plugins:
  - serverless-offline


functions:
  testConnection:
    handler: handler.testConnection
    events:
      - http:
          path: test
          method: get

  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post

  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get

  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put

  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
